### PR TITLE
0.0.8

### PR DESCRIPTION
**Pull request by TseHang**
Add & Update
- Update Spinner
- Add Init Input
- Add Login Screen
- Update useAsyncStorage
- Add `_add_to_package.json` 

Refactor
- refactor navigators
- refactor screens

### CODE REVIEW

**Comment by chihsuan** [comment]
@TseHang: Instead of providing the _add_to_package.json,  could you create an `init.js` or `init.ts` for users to update the package.json?

**Comment by TseHang** [comment]
@chihsuan  I need to test in real npm env, because install local react-native-template will not execute `setup.js` .

So maybe I need to try and test if it can work. Or we will really need a `init.js`.

**Comment by TseHang** [comment]
I will try publish beta version, and tell the results~~

**Comment by TseHang** [comment]
@chihsuan  @ching56  Please try, it will auto update `package.json` now.

**Pull request merged**
